### ISSUE TITLE
Setting hash size?

### ISSUE THREAD

**Issue by SzotsGabor** [vinc/littlewing#87]
Hi Vincent,

How do I set hash size in WB/UCI mode respectively?

**Comment by vinc** [comment]
Hi Gabor, for [WB](https://www.gnu.org/software/xboard/engine-intf.html) I implemented the `memory` command: https://github.com/vinc/littlewing/blob/v0.7.0/src/protocols/xboard.rs#L145 but there's nothing on my limited support of UCI.

Last week an [issue](https://github.com/vinc/littlewing/issues/86) has been reported on UCI so I can also add this to my TODO list. It'd be a good thing to support UCI more fully.

In the meantime it's also possible to run the binary with the option `-t 32` or `--tt 32` that would set the TT size to 32MB for example at launch: https://github.com/vinc/littlewing/blob/v0.7.0/src/main.rs#L49

**Comment by SzotsGabor** [comment]
Thanks Vincent. I tried -t 256 and the displayed memory size under Arena was 520 MB. When I tried -t 128 it was 205 MB. But it works.

**Comment by vinc** [comment]
It's strange I have much less overhead when I do the test in the console with the `top` command:

```
$ littlewing -st 128
> play # 129MB used here
< move e4
> hash 64
> play # 65MB used here
< move e5
> xboard

memory 256
level 40 60 0
new
go # 256MB used here
move e2e4
```
